using Microsoft.Data.SqlClient;
using RazorPageApplication.Enums;
using RazorPageApplication.Exceptions;
using RazorPageApplication.Helpers;
using RazorPageApplication.Interfaces;
using RazorPageApplication.Models;
using System.Data;

namespace RazorPageApplication.Services
{
    /// <summary>
    /// A repository for CRUD of <see cref="Teacher"/> as well as filtering.
    /// Every method is async and uses ADO.NET to access the MS-SQL database.
    /// </summary>
    public class TeacherRepositoryAsync : ITeacherRepository
    {
        /// <summary>
        /// Creates a <see cref="Teacher"/> and inserts it into the database.
        /// </summary>
        /// <param name="item">The <see cref="Teacher"/> object to be inserted in the database.
        /// The reference is also updated with the new autogenerated ID from the database.</param>
        /// <returns>A <see cref="Task"/> since this method is async.</returns>
        /// <exception cref="RepositoryException">Rethrown as a more detailed exception</exception>
        public async Task CreateAsync(Teacher item)
        {
            item.PhoneNumber = item.PhoneNumber.TrimPhoneNumber();
            if (string.IsNullOrEmpty(item.PhoneNumber) || item.PhoneNumber[0] == '0' || item.PhoneNumber[0] == '1')
            {
                throw new RepositoryException(RepositoryExceptionType.Create, "Ugyldigt tlf nr.");
            }
            string query = @"INSERT INTO Teacher
                            (TeacherName, Mail, TeacherPassword, PhoneNumber) 
                            OUTPUT INSERTED.TeacherID
                            Values(@TeacherName, @Mail, @TeacherPassword, @PhoneNumber)";
            await using (SqlConnection connection = new SqlConnection(Secret.ConnectionString))
            {
                try
                {
                    await connection.OpenAsync();
                    SqlCommand command = new SqlCommand(query, connection);
                    command.Parameters.AddWithValue("@TeacherName", item.Name);
                    command.Parameters.AddWithValue("@Mail", item.Mail);
                    command.Parameters.AddWithValue("@TeacherPassword", item.Password);
                    command.Parameters.AddWithValue("@PhoneNumber", item.PhoneNumber);
                    object? result = await command.ExecuteScalarAsync();
                    item.Id = Convert.ToInt32(result);
                }
                catch (SqlException sEx)
                {
                    sEx.PrintWithType();
                    throw new RepositoryException(RepositoryExceptionType.Create, "Ugyldigt input");
                }
                catch (Exception ex)
                {
                    ex.PrintWithType();
                    throw new RepositoryException(RepositoryExceptionType.Create, ex.GetFullMessage());
                }

            }
        }
        /// <summary>
        /// Deletes a <see cref="Teacher"/> in the database.
        /// </summary>
        /// <param name="item">The <see cref="Teacher"/> object to be deleted. Only its ID is used.</param>
        /// <returns></returns>
        /// <exception cref="RepositoryException"></exception>
        public async Task DeleteAsync(Teacher item)
        {
            string query = "DELETE FROM Teacher WHERE TeacherID = @TeacherID";
            using (SqlConnection connection = new SqlConnection(Secret.ConnectionString))
            {
                try
                {
                    SqlCommand command = new SqlCommand(query, connection);
                    await connection.OpenAsync();
                    command.Parameters.AddWithValue("@TeacherID", item.Id);
                    int rowsAffected = await command.ExecuteNonQueryAsync();
                    if (rowsAffected == 0)
                    {
                        throw new RepositoryException(RepositoryExceptionType.Delete, "No teacher found with the given Id");
                    }
                }
                catch (SqlException sEx)
                {
                    sEx.PrintWithType();
                    throw new RepositoryException(RepositoryExceptionType.Delete, "Ugyldig ID");
                }
                catch (Exception ex)
                {
                    ex.PrintWithType();
                    throw new RepositoryException(RepositoryExceptionType.Delete, ex.GetFullMessage());
                }
            }
        }
        /// <summary>
        /// Filters <see cref="Teacher"/> objects across all columns using the given criteria.
        /// Overload that defaults to <see cref="TeacherFilterBy.All"/>.
        /// </summary>
        /// <param name="filterCriteria">The text to search for. Matched with a SQL LIKE on every column.</param>
        /// <returns>A <see cref="Task"/> with a <see cref="List{T}"/> of matching <see cref="Teacher"/> objects.</returns>
        /// <exception cref="RepositoryException">Rethrown as a more detailed exception</exception>
        public async Task<List<Teacher>> FilterAsync(string filterCriteria)
        {
            return await FilterAsync(filterCriteria, TeacherFilterBy.All);
        }
        /// <summary>
        /// Filters <see cref="Teacher"/> objects on a single column chosen by <paramref name="teacherFilterBy"/>.
        /// The column is selected here so the criteria can be passed as a parameter and avoid SQL injection.
        /// </summary>
        /// <param name="filterCriteria">The text to search for. Matched with a SQL LIKE on the chosen column.</param>
        /// <param name="teacherFilterBy">The column to filter by. <see cref="TeacherFilterBy.All"/> searches every column.</param>
        /// <returns>A <see cref="Task"/> with a <see cref="List{T}"/> of matching <see cref="Teacher"/> objects.</returns>
        /// <exception cref="RepositoryException">Rethrown as a more detailed exception</exception>
        public async Task<List<Teacher>> FilterAsync(string filterCriteria, TeacherFilterBy teacherFilterBy)
        {
            string whereSql;
            switch (teacherFilterBy)
            {
                case TeacherFilterBy.TeacherID:
                    whereSql = "TeacherID LIKE @filterCriteria";
                    break;
                case TeacherFilterBy.TeacherName:
                    whereSql = "TeacherName LIKE @filterCriteria";
                    break;
                case TeacherFilterBy.Mail:
                    whereSql = "Mail LIKE @filterCriteria";
                    break;
                case TeacherFilterBy.PhoneNumber:
                    whereSql = "PhoneNumber LIKE @filterCriteria";
                    break;
                default:
                    whereSql = @"TeacherID LIKE @filterCriteria 
                               OR TeacherName LIKE @filterCriteria 
                               OR Mail LIKE @filterCriteria 
                               OR PhoneNumber LIKE @filterCriteria";
                    break;
            }
            string query = $"SELECT * FROM Teacher WHERE {whereSql}";
            List<Teacher> teachers = new List<Teacher>();
            using (SqlConnection connection = new SqlConnection(Secret.ConnectionString))
            {
                try
                {
                    await connection.OpenAsync();
                    SqlCommand command = new SqlCommand(query, connection);
                    command.Parameters.AddWithValue("@filterCriteria", $"%{filterCriteria}%");
                    SqlDataReader reader = await command.ExecuteReaderAsync();
                    while (await reader.ReadAsync())
                    {
                        int teacherID = reader.GetInt32("TeacherID");
                        string mail = reader.GetString("Mail");
                        string teacherPassword = reader.GetString("TeacherPassword");
                        string teacherName = reader.GetString("TeacherName");
                        string phoneNumber = reader.GetString("PhoneNumber");
                        Teacher teacher = new Teacher(id: teacherID, mail: mail, name: teacherName, password: teacherPassword, phoneNumber: phoneNumber);
                        teachers.Add(teacher);
                    }
                    await reader.CloseAsync();
                }
                catch (SqlException sEx)
                {
                    sEx.PrintWithType();
                    throw new RepositoryException(RepositoryExceptionType.Read, "Kan ikke indlæses");
                }
                catch (Exception ex)
                {
                    ex.PrintWithType();
                    throw new RepositoryException(RepositoryExceptionType.Read, ex.GetFullMessage());
                }
                return teachers;
            }
        }

        /// <summary>
        /// Gets a single <see cref="Teacher"/> from the database by its ID.
        /// </summary>
        /// <param name="id">The ID of the <see cref="Teacher"/> to look up.</param>
        /// <returns>A <see cref="Task"/> with the matching <see cref="Teacher"/>, or <c>null</c> if none is found.</returns>
        public async Task<Teacher?> GetAsync(int id)
        {
            string query = "SELECT * FROM Teacher WHERE TeacherID = @TeacherID";
            using (SqlConnection connection = new SqlConnection(Secret.ConnectionString))
            {

                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@TeacherID", id);
                await connection.OpenAsync();
                SqlDataReader reader = await command.ExecuteReaderAsync();
                if (await reader.ReadAsync())
                {
                    return new Teacher(id: id,
                        name: reader.GetString("TeacherName"),
                        mail: reader.GetString("Mail"),
                        password: reader.GetString("TeacherPassword"),
                        phoneNumber: reader.GetString("PhoneNumber"));
                }
                await reader.CloseAsync();
            }
            return null;
        }

        /// <summary>
        /// Gets every <see cref="Teacher"/> in the database.
        /// </summary>
        /// <returns>A <see cref="Task"/> with a <see cref="List{T}"/> of all <see cref="Teacher"/> objects.</returns>
        /// <exception cref="RepositoryException">Rethrown as a more detailed exception</exception>
        public async Task<List<Teacher>> GetAllAsync()
        {
            string query = "SELECT * FROM Teacher";
            List<Teacher> teachers = new List<Teacher>();
            using (SqlConnection connection = new SqlConnection(Secret.ConnectionString))
            {
                try
                {
                    await connection.OpenAsync();
                    SqlCommand command = new SqlCommand(query, connection);
                    SqlDataReader reader = await command.ExecuteReaderAsync();
                    while (await reader.ReadAsync())
                    {
                        int teacherID = reader.GetInt32("TeacherID");
                        string teacherName = reader.GetString("TeacherName");
                        string mail = reader.GetString("Mail");
                        string teacherPassword = reader.GetString("TeacherPassword");
                        string phoneNumber = reader.GetString("PhoneNumber");
                        Teacher teacher = new Teacher(id: teacherID, name: teacherName, mail: mail, password: teacherPassword, phoneNumber: phoneNumber);
                        teachers.Add(teacher);
                    }
                    await reader.CloseAsync();
                }
                catch (SqlException sEx)
                {
                    sEx.PrintWithType();
                    throw new RepositoryException(RepositoryExceptionType.Read, "Kan ikke indlæses");
                }
                catch (Exception ex)
                {
                    //ExceptionHelpers.PrintWithType(ex);
                    ex.PrintWithType();
                    throw new RepositoryException(RepositoryExceptionType.Read, ex.GetFullMessage());
                }
                return teachers;
            }
        }

        /// <summary>
        /// Updates an existing <see cref="Teacher"/> in the database. The row is matched on its ID.
        /// </summary>
        /// <param name="item">The <see cref="Teacher"/> object with the new values. Its ID selects the row to update.</param>
        /// <returns>A <see cref="Task"/> since this method is async.</returns>
        /// <exception cref="RepositoryException">Rethrown as a more detailed exception</exception>
        public async Task UpdateAsync(Teacher item)
        {
            string query = "UPDATE Teacher SET TeacherName = @TeacherName, Mail = @Mail, TeacherPassword = @TeacherPassword, PhoneNumber = @PhoneNumber WHERE TeacherID = @TeacherID";
            using (SqlConnection connection = new SqlConnection(Secret.ConnectionString))
            {
                try
                {
                    await connection.OpenAsync();
                    SqlCommand command = new SqlCommand(query, connection);
                    command.Parameters.AddWithValue("@TeacherID", item.Id);
                    command.Parameters.AddWithValue("@TeacherName", item.Name);
                    command.Parameters.AddWithValue("@Mail", item.Mail);
                    command.Parameters.AddWithValue("@TeacherPassword", item.Password);
                    command.Parameters.AddWithValue("@PhoneNumber", item.PhoneNumber);
                    await command.ExecuteNonQueryAsync();

                }
                catch (SqlException e)
                {
                    e.PrintWithType();
                    throw new RepositoryException(RepositoryExceptionType.Update, "Ugyldigt input");
                }
            }
        }


    }
}