using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using RazorPageApplication.Interfaces;
using RazorPageApplication.Models;
using System.ComponentModel.DataAnnotations;

namespace RazorPageApplication.Pages.Photos
{
    public class CreatePhotoModel : PageModel
    {
        #region Instance fields
        private IRepositoryAsync<Photo> _repo;
        private IRepositoryAsync<Photographer> _photographerRepo;
        private IRepositoryAsync<Student> _studentRepo;

        private IWebHostEnvironment _webHostEnvironment;
        #endregion

        #region Properties
        [BindProperty]
        public Photo NewPhoto { get; set; }

        [BindProperty]
        public IFormFile Photo { get; set; }

        [BindProperty]
        [Required]
        public string PhotographerId { get; set; }

        [BindProperty]
        [Required]
        public string StudentId { get; set; }

        [BindProperty]
        public DateTime Date { get; set; }

        [BindProperty]
        public IEnumerable<SelectListItem> PhotographerSelect { get; set; }
        [BindProperty]
        public IEnumerable<SelectListItem> StudentSelect { get; set; }

        #endregion

        #region Constructors
        public CreatePhotoModel(IRepositoryAsync<Photo> photoRepository, IRepositoryAsync<Photographer> photographerRepository, IRepositoryAsync<Student> studentRepository, IWebHostEnvironment webHostEnvironment)
        {
            _repo = photoRepository;
            _photographerRepo = photographerRepository;
            _studentRepo = studentRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        #endregion

        #region Methods
        public async Task OnGet()
        {
            NewPhoto = new Photo();

            List<Photographer> photographers = await _photographerRepo.GetAllAsync();
            PhotographerSelect = photographers.Select(p => new SelectListItem { Value = Convert.ToString(p.Id), Text = $"{p.Name} - {p.Mail}" });
            List<Student> students = await _studentRepo.GetAllAsync();
            StudentSelect = students.Select(p => new SelectListItem { Value = Convert.ToString(p.Id), Text = $"{p.Name} - {p.SchoolClass.Name} - {p.SchoolClass.Year}" });
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                await OnGet();
                return Page();
            }
            // Making sure FilePath is not null
            NewPhoto.FilePath = "";
            try
            {
                NewPhoto.Photographer = await _photographerRepo.GetAsync(Convert.ToInt32(PhotographerId));
                NewPhoto.Student = await _studentRepo.GetAsync(Convert.ToInt32(StudentId));
                // We call create first to get the autogenerated identity id before we assign the filename
                await _repo.CreateAsync(NewPhoto);
                if (Photo != null)

                    if (Photo.FileName != null)
                    {
                        // Now that we have the autogenerated id we can create the correct filename
                        NewPhoto.FilePath = await ProcessUploadedFile();
                    }
                // The new filename needs to reach the database as well. Thus we update
                await _repo.UpdateAsync(NewPhoto);
                return RedirectToPage("Index");
            }

            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                ModelState.AddModelError(string.Empty, ex.Message);
                await OnGet();
                return Page();
            }
        }

        private async Task<string> ProcessUploadedFile()
        {
            string uniqueFileName = null;
            if (Photo != null)
            {
                Student student = await _studentRepo.GetAsync(Convert.ToInt32(StudentId));
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images/Photos");
                string extension = Path.GetExtension(Photo.FileName);
                uniqueFileName = $"{student.SchoolClass.School.Name}_{student.SchoolClass.Name}_{student.Name}_{NewPhoto.Date.Day}-{NewPhoto.Date.Month}-{NewPhoto.Date.Year}_ID-{NewPhoto.Id}{extension}"
                    .ToLower()
                    .Replace(" ", "_");
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        } 
        #endregion
    }
}
